### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by lcscs12345** [ikmb/amino_acid_encoding_deep_learning_applications#1]
Hi @HeshamElAbd,

Thank you for sharing your code and data. I am interested in your PPI analysis and models.

Could you share the output files of PrepearKmersEncodedSequences.py? 
- trainingDataSetUniquePairs.pickle
- testDataSetUniquePairs.pickle​

This would be helpful for generating embeddings using your scripts. I might need to ask for some other files later if that is OK.

Many thanks,
Lim

**Comment by HeshamElAbd** [comment]
Hi @lcscs12345 , many thanks for your kind words, it is much appreciated. 

So, the training file can be downloaded from: 
https://order.ikmb.uni-kiel.de/media/PPI_Data.zip  

Sure, please feel free to contact me anytime. 
Stay healthy and safe, 
Hesham

**Comment by lcscs12345** [comment]
Thanks @HeshamElAbd

I have looked into these files before. Would like to get trainingDataSetUniquePairs.pickle and testDataSetUniquePairs.pickle if you still have them.​

**Comment by HeshamElAbd** [comment]
Hi @lcscs12345, 

sorry for the misunderstanding. So, at the moment, I just deployed the final training tensors, ready for training the models. I think the intermediate files, but I am not quite sure, are still available at my pc at work. At the moment we are in a lockdown here in Germany, so once it is allowed to go back to the office, I will get back to you. Also, I think you can generate these files using the script and the databases that are publicly available. Thanks a lot for your understanding .

**Comment by HeshamElAbd** [comment]
Hi @lcscs12345 Chun if I may, 

So, I did manage to access my intermediate files at work. kindly find the files you asked for in the resources directory. if you further files, please let me know.
