### ISSUE TITLE
BLOSUM.csv location

### ISSUE THREAD

**Issue by tijeco** [ikmb/amino_acid_encoding_deep_learning_applications#2]
@HeshamElAbd  This is really incredible work! I'd like to play around with some of the embedding methods used here, and was wondering where the location of BLOSUM.csv file is?

**Comment by HeshamElAbd** [comment]
Hi @tijeco Thanks a lot, I am glad you found the repository useful. I have uploaded the BLOSUM.csv to the resource directory. Please let me know if I can help with anything else.
